name: Tag

on:
  push:
    branches:
    - main
    paths-ignore:
    - 'custom_domains/**'

jobs:
  tag:
    name: Push Git Tag
    runs-on: ubuntu-latest
    steps:
      - name: Tag and Create Release
        uses: rymndhng/release-on-push-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          bump_version_scheme: patch
          tag_prefix: ""
